spring:
  application:
    name: gaetteok
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/gaetteok?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:gaetteok}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

ncloud:
  accessKey: ${NCP_ACCESS_KEY}
  secretKey: ${NCP_SECRET_KEY}
  bucketName: gaetteok-image
