spring:
  application:
    name: gaetteok
  jpa:
    hibernate:
      ddl-auto: create-drop # 샘플 데이터 세팅을 위한 임시 조치 (FE에서 데이터 넣기 시작하면 빠져야 함)
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

ncloud:
  accessKey: ${NCP_ACCESS_KEY}
  secretKey: ${NCP_SECRET_KEY}
  bucketName: gaetteok-image

springdoc:
  api-docs:
    path: /docs
    groups:
      enabled: true
  swagger-ui:
    path: /docs/swagger
    enabled: true
    groups-order: asc
    tags-sorter: alpha
  cache:
    disabled: true
weather:
  api-key: ${WEATHER_API_KEY}
  api-path: ${WEATHER_API_PATH}

swagger:
  server:
    url: ${SWAGGER_SERVER_URL}
