spring:
  application:
    name: gaetteok
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

ncloud:
  accessKey: ${NCP_ACCESS_KEY}
  secretKey: ${NCP_SECRET_KEY}
  bucketName: gaetteok-image

springdoc:
  swagger-ui:
    url: /docs/openapi3.json
    path: /docs/swagger
