spring:
  application:
    name: gaetteok
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${{ secrets.DB_URL }}
    username: ${{ secrets.DB_USERNAME }}
    password: ${{ secrets.DB_PASSWORD }}
    driver-class-name: com.mysql.cj.jdbc.Driver

ncloud:
  accessKey: ${{ secrets.NCP_ACCESS_KEY }}
  secretKey: ${{ secrets.NCP_SECRET_KEY }}
  bucketName: gaetteok-image
