spring:
  application:
    name: gaetteok
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

ncloud:
  accessKey: ${NCP_ACCESS_KEY}
  secretKey: ${NCP_SECRET_KEY}
  bucketName: gaetteok-image

springdoc:
  api-docs:
    path: /docs
    groups:
      enabled: true
  swagger-ui:
    path: /docs/swagger
    enabled: true
    groups-order: asc
    tags-sorter: alpha
  cache:
    disabled: true
weather:
  apiKey: ${WEATHER_API_KEY}
  apiPath: ${WEATHER_API_PATH}

swagger:
  server:
    url: ${SWAGGER_SERVER_URL}

jwt:
  secret: ${JWT_SECRET}

pawpaw:
  admin:
    token: ${PAWPAW_ADMIN_TOKEN}
